project:
  name: go-broadcast
  binary: go-broadcast
  module: github.com/mrz1836/go-broadcast
  main: ./cmd/go-broadcast/main.go

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
    - "-X main.buildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./cmd/go-broadcast"

test:
  # Match CI timeout configuration (TEST_TIMEOUT_RACE_COVER in .env.base)
  # Default magex timeout is 10m which was killing tests prematurely
  timeout: 30m
