title: "GoFortress Coverage Dashboard"
description: "Coverage tracking and reporting for go-broadcast"

# Exclude directories and files from Jekyll processing
exclude:
  - plans/
  - .github/coverage/
  - internal/
  - cmd/
  - test/
  - examples/
  - Makefile
  - go.mod
  - go.sum
  - "*.go"
  - .golangci.json
  - .goreleaser.yml
  - .gitleaks.toml
  - .gitpod.yml
  - .pre-commit-config.yaml
  - CONTRIBUTING.md
  - CITATION.cff

# Theme (optional)
theme: jekyll-theme-minimal

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Additional settings
lang: en
timezone: America/New_York